FROM stickerbook-omega-llm:experiment

COPY runtime/omega/openshell-entrypoint.sh /usr/local/bin/stickerbook-openshell-entrypoint
RUN chmod 0755 /usr/local/bin/stickerbook-openshell-entrypoint

USER 65534:65534
ENTRYPOINT ["/usr/local/bin/stickerbook-openshell-entrypoint"]
CMD []
