# LOCAL POWERED DEV only: ordinary Docker does not reproduce OpenShell mediation.
ARG BASE_IMAGE=omega-jev:experiment
FROM ${BASE_IMAGE}
USER 65534:65534
WORKDIR /PeTTa
ENTRYPOINT ["sh", "run.sh", "run.metta"]
