"""Bounded conversational provider for StickerBook's OmegaLLM loop.

OmegaLLM is linguistic mediation, not world authority. It receives one
host-composed StickerBook request from the stickerbookrpc channel and may return
child-facing language plus one schema-bounded semantic goal.

The provider intentionally ignores Omega's generated prompt. The current
StickerBook request is the sole task input. The only executable Omega command
left in the allowlist is the zero-argument `sb-return` skill, which returns a
staged JSON result to the host. No model-generated bytes become executable.
"""

from __future__ import annotations

import importlib
import json
import math
import os
import sys
import urllib.error
import urllib.request

import providers
from config import config_get_by_key
from src.logger import get_logger

logger = get_logger(__name__)

DEFAULT_MODEL = "z-ai/glm-5.2"
DEFAULT_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_TIMEOUT = 40
MAX_REPLY_CHARS = 1000

_ALLOWED_GOAL_FIELDS = frozenset({
    "subject", "intent", "behavior", "target", "facing", "scale",
})
_ALLOWED_INTENTS = frozenset({
    "control", "animate", "move", "move-and-animate",
})


def _helper_modules():
    found = []
    for name in ("helper", "src.helper"):
        module = sys.modules.get(name)
        if module is not None and hasattr(module, "LLM_COMMANDS"):
            found.append(module)
    if not found:
        import helper as fallback  # noqa: PLC0415
        found.append(fallback)
    return found


def harden_llm_commands():
    """Leave exactly one zero-argument executable command: sb-return."""
    for module in _helper_modules():
        module.LLM_COMMANDS.clear()
        module.LLM_COMMANDS.add("sb-return")
        module.STATIC_LLM_COMMANDS.clear()
        module.STATIC_LLM_COMMANDS.add("sb-return")
    logger.info("[stickerbook-llm] LLM_COMMANDS narrowed to ['sb-return']")


class OpenShellOpenRouterTransport:
    """OpenRouter chat completion through an OpenShell provider placeholder."""

    def __init__(self, url: str, timeout: int):
        self.url = url
        self.timeout = timeout

    def __call__(self, payload: dict) -> dict:
        token = os.environ.get("OPENROUTER_API_KEY", "").strip()
        if not token:
            raise RuntimeError("OpenShell provider placeholder is unavailable")
        request = urllib.request.Request(
            self.url,
            data=json.dumps(payload, separators=(",", ":")).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer " + token,
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                raw = response.read(1024 * 1024 + 1)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")[:300]
            raise RuntimeError("HTTP %s: %s" % (exc.code, detail)) from exc
        except urllib.error.URLError as exc:
            raise RuntimeError("network failure: " + str(exc.reason)) from exc
        if len(raw) > 1024 * 1024:
            raise RuntimeError("OpenRouter response too large")
        decoded = json.loads(raw.decode("utf-8"))
        if not isinstance(decoded, dict):
            raise RuntimeError("OpenRouter returned a non-object")
        return decoded


def _finite_number(value):
    if isinstance(value, bool):
        raise ValueError("boolean is not numeric")
    number = float(value)
    if not math.isfinite(number):
        raise ValueError("non-finite number")
    return number


def _clean_target(raw):
    if not isinstance(raw, dict):
        raise ValueError("invalid target")
    kind = raw.get("kind")
    if kind == "sticker" and set(raw) == {"kind", "id"}:
        sticker_id = raw.get("id")
        if isinstance(sticker_id, str) and 0 < len(sticker_id) <= 160:
            return {"kind": "sticker", "id": sticker_id}
        raise ValueError("invalid sticker target")
    if kind == "point" and set(raw) == {"kind", "x", "y"}:
        x = _finite_number(raw.get("x"))
        y = _finite_number(raw.get("y"))
        if 0.0 <= x <= 1.0 and 0.0 <= y <= 1.0:
            return {"kind": "point", "x": x, "y": y}
    raise ValueError("invalid target")


def clean_goal(raw):
    """Validate the same semantic envelope the host validates again."""
    if raw is None:
        return None
    if not isinstance(raw, dict) or set(raw) - _ALLOWED_GOAL_FIELDS:
        raise ValueError("invalid goal fields")

    subject = raw.get("subject")
    if not isinstance(subject, str) or not subject or len(subject) > 160:
        raise ValueError("invalid goal subject")
    intent = raw.get("intent", "control")
    if intent not in _ALLOWED_INTENTS:
        raise ValueError("invalid goal intent")

    goal = {"subject": subject, "intent": intent}

    if "behavior" in raw:
        behavior = raw["behavior"]
        if not isinstance(behavior, str) or not behavior or len(behavior) > 80:
            raise ValueError("invalid goal behavior")
        goal["behavior"] = behavior

    if "target" in raw:
        goal["target"] = _clean_target(raw["target"])

    if "facing" in raw:
        facing = raw["facing"]
        if facing not in ("left", "right"):
            raise ValueError("invalid goal facing")
        goal["facing"] = facing

    if "scale" in raw:
        scale = _finite_number(raw["scale"])
        if not 0.90 <= scale <= 1.10:
            raise ValueError("invalid goal scale")
        goal["scale"] = scale

    return goal


def _extract_content(body: dict) -> str:
    choices = body.get("choices")
    if not isinstance(choices, list) or not choices:
        raise ValueError("missing choices")
    first = choices[0]
    if not isinstance(first, dict):
        raise ValueError("invalid choice")
    message = first.get("message")
    if not isinstance(message, dict):
        raise ValueError("invalid message")
    content = message.get("content")
    if not isinstance(content, str) or not content.strip():
        raise ValueError("missing content")
    return content.strip()


def _parse_json_object(text: str) -> dict:
    """Strict JSON first; tolerate only a single fenced JSON object."""
    candidate = text.strip()
    if candidate.startswith("```") and candidate.endswith("```"):
        lines = candidate.splitlines()
        if len(lines) >= 3 and lines[0].strip().lower() in (
                "```json", "```"):
            candidate = "\n".join(lines[1:-1]).strip()
    decoded = json.loads(candidate)
    if not isinstance(decoded, dict):
        raise ValueError("response is not an object")
    return decoded


SYSTEM_PROMPT = """You are OmegaLLM inside StickerBook, a child-facing language
translator. Reply warmly and briefly to the child, and optionally translate the
request into ONE semantic goal. You do not control the page and you never emit
commands, code, tool calls, coordinates outside the provided page geometry, or
claims that an action succeeded.

Return exactly one JSON object and no other text:
{"reply":"...", "goal": optional-object}

If no page action is clearly requested, omit goal. If a goal is appropriate,
use only these fields:
- subject: exact sticker instance id visible in scene
- intent: control | animate | move | move-and-animate
- behavior: optional short desired behavior/clip word
- target: optional {"kind":"sticker","id":"..."} or
          {"kind":"point","x":0..1,"y":0..1}
- facing: optional left | right
- scale: optional number from 0.90 through 1.10

Use the child's transient reference only as context. Never invent authority.
The host independently validates every goal and the authority kernel makes every
world-mutation decision."""


class StickerBookLLMProvider(providers.LLMProvider):

    def __init__(self):
        super().__init__()
        self.model = DEFAULT_MODEL
        self.transport = None

    def start(self) -> None:
        harden_llm_commands()
        self.model = str(config_get_by_key(
            "stickerbookLlmModel", DEFAULT_MODEL)).strip() or DEFAULT_MODEL
        url = str(config_get_by_key(
            "stickerbookLlmUrl", DEFAULT_URL)).strip() or DEFAULT_URL
        timeout = int(config_get_by_key(
            "stickerbookLlmTimeout", DEFAULT_TIMEOUT))
        self.transport = OpenShellOpenRouterTransport(url, timeout)
        rpc = importlib.import_module("stickerbookrpc")
        rpc.set_provider_ready("omegallm")
        logger.info("[stickerbook-llm] provider ready; model=%s", self.model)

    def stop(self) -> None:
        self.transport = None

    def chat(self, prompt: str, max_tokens: int = 6000,
             reasoning_mode: str = "medium") -> str:
        # Omega's prompt is intentionally ignored. The host-composed request
        # from the communication channel is the entire task surface.
        harden_llm_commands()
        rpc = importlib.import_module("stickerbookrpc")
        request = rpc.current_request("omegallm")
        if not isinstance(request, dict):
            return ""

        safe_input = {
            "text": request.get("text"),
            "principal": request.get("principal"),
            "scene": request.get("scene"),
            "reference": request.get("reference"),
        }
        try:
            body = self.transport({
                "model": self.model,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": json.dumps(
                        safe_input, separators=(",", ":"), sort_keys=True)},
                ],
                "max_tokens": min(int(max_tokens), 1200),
                "temperature": 0.2,
            })
            decoded = _parse_json_object(_extract_content(body))
            if set(decoded) - {"reply", "goal"}:
                raise ValueError("unknown response field")
            reply = decoded.get("reply")
            if not isinstance(reply, str) or not reply.strip():
                raise ValueError("missing reply")
            reply = reply.strip()
            if len(reply) > MAX_REPLY_CHARS:
                raise ValueError("reply too long")
            result = {"ok": True, "reply": reply}
            goal = clean_goal(decoded.get("goal"))
            if goal is not None:
                result["goal"] = goal
        except Exception as exc:  # every model/provider/schema failure is bounded
            logger.warning(
                "[stickerbook-llm] failed closed: %s: %s",
                type(exc).__name__, str(exc)[:300])
            result = {"ok": False, "error": "omegallm-failed-closed"}

        if not rpc.stage_result(result):
            logger.warning("[stickerbook-llm] failed to stage bounded response")
            return ""
        return "sb-return"


def loadOmegaPlugin():
    # Early hardening, repeated at start/chat after all plugins have loaded.
    harden_llm_commands()
    providers.registerLLMProvider("StickerBookLLM", StickerBookLLMProvider())
