"""Bounded conversational provider for StickerBook's OmegaLLM loop.

OmegaLLM is linguistic mediation, not world authority. It receives one
host-composed StickerBook request from the stickerbookrpc channel and may return
child-facing language plus one schema-bounded semantic goal.

The provider intentionally ignores Omega's generated prompt. The current
StickerBook request is the sole task input. The only executable Omega command
left in the allowlist is the zero-argument `sb-return` skill, which returns a
staged JSON result to the host. No model-generated bytes become executable.
"""

from __future__ import annotations

import importlib
import json
import math
import os
import re
import sys
import urllib.error
import urllib.request

import providers
from config import config_get_by_key
from src.logger import get_logger

logger = get_logger(__name__)

DEFAULT_TIMEOUT = 40
MAX_REPLY_CHARS = 1000
_MODEL_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,119}$")
_INPUT_EVENT_RE = re.compile(r"^input-event-[1-9][0-9]{0,15}$")

INFERENCE_PRESETS = {
    "asicloud": {
        "label": "Sponsored ASI Cloud",
        "description": "Sponsored MiniMax inference supplied by ASI Cloud.",
        "default_model": "minimax/minimax-m3",
        "env": "ASI_API_KEY",
        "url": "https://inference.asicloud.cudos.org/v1/chat/completions",
        "protocol": "openai",
        "sponsored": True,
        "model_locked": True,
    },
    "anthropic": {
        "label": "Anthropic",
        "description": "Direct Claude inference using a configured Anthropic API key.",
        "default_model": "claude-opus-4-8",
        "env": "ANTHROPIC_API_KEY",
        "url": "https://api.anthropic.com/v1/messages",
        "protocol": "anthropic",
        "sponsored": False,
        "model_locked": False,
    },
    "openai": {
        "label": "OpenAI",
        "description": "Direct OpenAI inference using a configured OpenAI API key.",
        "default_model": "gpt-5.5",
        "env": "OPENAI_API_KEY",
        "url": "https://api.openai.com/v1/chat/completions",
        "protocol": "openai",
        "sponsored": False,
        "model_locked": False,
    },
    "openrouter": {
        "label": "OpenRouter",
        "description": "OpenRouter inference; the responsible adult may choose an OpenRouter model id.",
        "default_model": "z-ai/glm-5.2",
        "env": "OPENROUTER_API_KEY",
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "protocol": "openai",
        "sponsored": False,
        "model_locked": False,
    },
    "asione": {
        "label": "ASI:One",
        "description": "Direct ASI:One inference using a configured ASI:One API key.",
        "default_model": "asi1-ultra",
        "env": "ASIONE_API_KEY",
        "url": "https://api.asi1.ai/v1/chat/completions",
        "protocol": "openai",
        "sponsored": False,
        "model_locked": False,
    },
}

_ALLOWED_GOAL_FIELDS = frozenset({
    "subject", "intent", "behavior", "target", "facing", "scale",
    "demonstration", "label", "pattern",
})
_ALLOWED_INTENTS = frozenset({
    "control", "animate", "move", "move-and-animate", "bind-demonstration",
    "remember-pattern", "perform-pattern",
})


def _helper_modules():
    found = []
    for name in ("helper", "src.helper"):
        module = sys.modules.get(name)
        if module is not None and hasattr(module, "LLM_COMMANDS"):
            found.append(module)
    if not found:
        import helper as fallback  # noqa: PLC0415
        found.append(fallback)
    return found


def harden_llm_commands():
    """Leave exactly one zero-argument executable command: sb-return."""
    for module in _helper_modules():
        module.LLM_COMMANDS.clear()
        module.LLM_COMMANDS.add("sb-return")
        module.STATIC_LLM_COMMANDS.clear()
        module.STATIC_LLM_COMMANDS.add("sb-return")
    logger.info("[stickerbook-llm] LLM_COMMANDS narrowed to ['sb-return']")


def inference_options() -> list[dict]:
    """Secret-free provider metadata for the responsible-adult UI."""
    options = []
    for provider_id, preset in INFERENCE_PRESETS.items():
        options.append({
            "id": provider_id,
            "label": preset["label"],
            "description": preset["description"],
            "default_model": preset["default_model"],
            "model_locked": bool(preset["model_locked"]),
            "sponsored": bool(preset["sponsored"]),
            "available": bool(os.environ.get(preset["env"], "").strip()),
        })
    return options


def clean_inference(raw) -> tuple[str, str, dict]:
    if not isinstance(raw, dict) or set(raw) != {"provider", "model"}:
        raise ValueError("invalid inference selection")
    provider_id = raw.get("provider")
    model = raw.get("model")
    if provider_id not in INFERENCE_PRESETS:
        raise ValueError("unknown inference provider")
    if not isinstance(model, str) or not _MODEL_RE.fullmatch(model.strip()):
        raise ValueError("invalid inference model")
    model = model.strip()
    preset = INFERENCE_PRESETS[provider_id]
    if preset["model_locked"] and model != preset["default_model"]:
        raise ValueError("sponsored model is fixed")
    if not os.environ.get(preset["env"], "").strip():
        raise RuntimeError("selected inference provider is not configured")
    return provider_id, model, preset


class _HTTPTransport:
    def __init__(self, url: str, env_var: str, timeout: int):
        self.url = url
        self.env_var = env_var
        self.timeout = timeout

    def _token(self) -> str:
        token = os.environ.get(self.env_var, "").strip()
        if not token:
            raise RuntimeError("%s provider placeholder unavailable" % self.env_var)
        return token

    def _request(self, payload: dict, headers: dict) -> dict:
        request = urllib.request.Request(
            self.url,
            data=json.dumps(payload, separators=(",", ":")).encode("utf-8"),
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                raw = response.read(1024 * 1024 + 1)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")[:300]
            raise RuntimeError("HTTP %s: %s" % (exc.code, detail)) from exc
        except urllib.error.URLError as exc:
            raise RuntimeError("network failure: " + str(exc.reason)) from exc
        if len(raw) > 1024 * 1024:
            raise RuntimeError("inference response too large")
        decoded = json.loads(raw.decode("utf-8"))
        if not isinstance(decoded, dict):
            raise RuntimeError("inference backend returned a non-object")
        return decoded


class OpenAICompatibleTransport(_HTTPTransport):
    def complete(self, model: str, safe_input: dict, max_tokens: int) -> str:
        body = self._request({
            "model": model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": json.dumps(
                    safe_input, separators=(",", ":"), sort_keys=True)},
            ],
            "max_tokens": min(int(max_tokens), 1200),
        }, {
            "Content-Type": "application/json",
            "Authorization": "Bearer " + self._token(),
        })
        return _extract_content(body)


class AnthropicTransport(_HTTPTransport):
    def complete(self, model: str, safe_input: dict, max_tokens: int) -> str:
        body = self._request({
            "model": model,
            "system": SYSTEM_PROMPT,
            "messages": [{
                "role": "user",
                "content": json.dumps(
                    safe_input, separators=(",", ":"), sort_keys=True),
            }],
            "max_tokens": min(int(max_tokens), 1200),
        }, {
            "Content-Type": "application/json",
            "x-api-key": self._token(),
            "anthropic-version": "2023-06-01",
        })
        blocks = body.get("content")
        if not isinstance(blocks, list):
            raise ValueError("missing content")
        text = "".join(
            block.get("text", "")
            for block in blocks
            if isinstance(block, dict) and block.get("type") == "text"
        ).strip()
        if not text:
            raise ValueError("missing content")
        return text

def _finite_number(value):
    if isinstance(value, bool):
        raise ValueError("boolean is not numeric")
    number = float(value)
    if not math.isfinite(number):
        raise ValueError("non-finite number")
    return number


def _clean_target(raw):
    if not isinstance(raw, dict):
        raise ValueError("invalid target")
    kind = raw.get("kind")
    if kind == "sticker" and set(raw) == {"kind", "id"}:
        sticker_id = raw.get("id")
        if isinstance(sticker_id, str) and 0 < len(sticker_id) <= 160:
            return {"kind": "sticker", "id": sticker_id}
        raise ValueError("invalid sticker target")
    if kind == "point" and set(raw) == {"kind", "x", "y"}:
        x = _finite_number(raw.get("x"))
        y = _finite_number(raw.get("y"))
        if 0.0 <= x <= 1.0 and 0.0 <= y <= 1.0:
            return {"kind": "point", "x": x, "y": y}
    raise ValueError("invalid target")


def clean_goal(raw):
    """Validate the same semantic envelope the host validates again."""
    if raw is None:
        return None
    if not isinstance(raw, dict) or set(raw) - _ALLOWED_GOAL_FIELDS:
        raise ValueError("invalid goal fields")

    subject = raw.get("subject")
    if not isinstance(subject, str) or not subject or len(subject) > 160:
        raise ValueError("invalid goal subject")
    intent = raw.get("intent", "control")
    if intent not in _ALLOWED_INTENTS:
        raise ValueError("invalid goal intent")

    if intent in ("remember-pattern", "perform-pattern"):
        if set(raw) - {"subject", "intent", "label", "pattern"}:
            raise ValueError("invalid pattern goal fields")
        goal = {"subject": subject, "intent": intent}
        label = raw.get("label")
        if label is not None:
            # Match the host's valid_label bound and canonical whitespace.
            if not isinstance(label, str) or not 0 < len(label.strip()) <= 48 \
                    or any(ch in ":\r\n\t" for ch in label):
                raise ValueError("invalid pattern label")
            goal["label"] = " ".join(label.split())
        reference = raw.get("pattern")
        if reference is not None:
            if not isinstance(reference, str) or not reference \
                    or len(reference) > 64 or ":" in reference:
                raise ValueError("invalid pattern reference")
            goal["pattern"] = reference
        if intent == "remember-pattern" and "label" not in goal:
            raise ValueError("missing pattern label")
        if intent == "perform-pattern" and not ({"label", "pattern"} & goal.keys()):
            raise ValueError("missing pattern reference")
        return goal
    if {"label", "pattern"} & raw.keys():
        raise ValueError("pattern fields require pattern intent")

    if intent == "bind-demonstration":
        if set(raw) != {"subject", "intent", "demonstration"}:
            raise ValueError("invalid demonstration goal fields")
        event_id = raw["demonstration"]
        if not isinstance(event_id, str) or not _INPUT_EVENT_RE.fullmatch(event_id):
            raise ValueError("invalid demonstration reference")
        return {"subject": subject, "intent": intent,
                "demonstration": event_id}
    if "demonstration" in raw:
        raise ValueError("demonstration requires bind intent")

    goal = {"subject": subject, "intent": intent}

    if "behavior" in raw:
        behavior = raw["behavior"]
        if not isinstance(behavior, str) or not behavior or len(behavior) > 80:
            raise ValueError("invalid goal behavior")
        goal["behavior"] = behavior

    if "target" in raw:
        goal["target"] = _clean_target(raw["target"])

    if "facing" in raw:
        facing = raw["facing"]
        if facing not in ("left", "right"):
            raise ValueError("invalid goal facing")
        goal["facing"] = facing

    if "scale" in raw:
        scale = _finite_number(raw["scale"])
        if not 0.90 <= scale <= 1.10:
            raise ValueError("invalid goal scale")
        goal["scale"] = scale

    return goal


def validate_demonstration_goal(goal, scene):
    """Admit only a supported event offered in this turn's bounded scene."""
    if goal is None or goal.get("intent") != "bind-demonstration":
        return
    interaction = scene.get("interaction") if isinstance(scene, dict) else None
    signals = interaction.get("signals") if isinstance(interaction, dict) else None
    if not isinstance(signals, list):
        raise ValueError("missing current interaction")
    if not any(isinstance(signal, dict)
               and signal.get("kind") == "page-path"
               and signal.get("sourceEvent") == goal["demonstration"]
               for signal in signals):
        raise ValueError("demonstration not in current interaction")


def _extract_content(body: dict) -> str:
    choices = body.get("choices")
    if not isinstance(choices, list) or not choices:
        raise ValueError("missing choices")
    first = choices[0]
    if not isinstance(first, dict):
        raise ValueError("invalid choice")
    message = first.get("message")
    if not isinstance(message, dict):
        raise ValueError("invalid message")
    content = message.get("content")
    if not isinstance(content, str) or not content.strip():
        raise ValueError("missing content")
    return content.strip()


def _parse_json_object(text: str) -> dict:
    """Strict JSON first; tolerate only a single fenced JSON object."""
    candidate = text.strip()
    if candidate.startswith("```") and candidate.endswith("```"):
        lines = candidate.splitlines()
        if len(lines) >= 3 and lines[0].strip().lower() in (
                "```json", "```"):
            candidate = "\n".join(lines[1:-1]).strip()
    decoded = json.loads(candidate)
    if not isinstance(decoded, dict):
        raise ValueError("response is not an object")
    return decoded


SYSTEM_PROMPT = """You are OmegaLLM inside StickerBook, a child-facing language
translator. Reply warmly and briefly to the child, and optionally translate the
request into ONE semantic goal. You do not control the page and you never emit
commands, code, tool calls, coordinates outside the provided page geometry, or
claims that an action succeeded.

Return exactly one JSON object and no other text:
{"reply":"...", "goal": optional-object}

If no page direction, demonstration binding, or pattern-memory request is
clearly expressed, omit goal. If a goal is appropriate,
use only these fields:
- subject: exact sticker instance id visible in scene
- intent: control | animate | move | move-and-animate | bind-demonstration |
          remember-pattern | perform-pattern
- behavior: optional short desired behavior/clip word
- target: optional {"kind":"sticker","id":"..."} or
          {"kind":"point","x":0..1,"y":0..1}
- facing: optional left | right
- scale: optional number from 0.90 through 1.10
- demonstration: for bind-demonstration only, one exact `sourceEvent` from a
  `page-path` signal in THIS `scene.interaction`; use no other goal fields
  besides subject, intent, and demonstration for that intent

For a child referring to a demonstration, you may semantically select one
current page-path event from `scene.interaction`. Use the utterance, scene,
and factual sourceEvent relationships; do not simply pick the newest signal.
The host retains path geometry. You do not receive its trajectory samples.
Binding records a reference only; it does not move or teach a sticker.

For "Remember that as your happy dance", use remember-pattern with subject
and label. The host resolves "that" from actual recent governed actions; you
must never supply steps, action keys, historical selections, or trajectories.
For "Do your happy dance", use perform-pattern with subject and label (or a
known pattern id in pattern). The host resolves the existing memory and Jev
chooses among fresh legal actions. Never invent a pattern id. Pattern intents
may contain only subject, intent, label, and pattern. A label has 1..48 trimmed
characters and no colon, newline, carriage return, or tab. A pattern id has
1..64 characters and no colon. Remember requires label; perform requires label
or pattern. Do not claim remembering or performance succeeded before the host
reports it. Page paths and sticker-drag trajectories are not learned movement
patterns; do not promise to remember their geometry through these intents.

The scene may include a `child_help` object. Treat that object as the
authoritative child-facing documentation for questions such as "how do I play?",
"what can you do?", or "what happens if I double-tap?". Explain it in simple
language. Do not invent parent/operator controls, computer access, extra tools,
network powers, saving/publishing powers, or capabilities that are not present
in the scene or child_help.

Use the child's transient reference only as context. Never invent authority.
Never tell the child that a requested action succeeded merely because you asked
for it; only authoritative state/receipts can establish success. The host
independently validates every goal and the authority kernel makes every
world-mutation decision."""


class StickerBookLLMProvider(providers.LLMProvider):

    def __init__(self):
        super().__init__()
        self.timeout = DEFAULT_TIMEOUT

    def start(self) -> None:
        harden_llm_commands()
        self.timeout = int(config_get_by_key(
            "stickerbookLlmTimeout", DEFAULT_TIMEOUT))
        rpc = importlib.import_module("stickerbookrpc")
        rpc.set_provider_ready("omegallm", {
            "inference_options": inference_options(),
        })
        logger.info(
            "[stickerbook-llm] configured inference lanes=%s",
            [item["id"] for item in inference_options() if item["available"]],
        )

    def stop(self) -> None:
        return None

    def _transport(self, preset: dict):
        cls = (AnthropicTransport if preset["protocol"] == "anthropic"
               else OpenAICompatibleTransport)
        return cls(preset["url"], preset["env"], self.timeout)

    def chat(self, prompt: str, max_tokens: int = 6000,
             reasoning_mode: str = "medium") -> str:
        # Omega's prompt is intentionally ignored. The host-composed request
        # from the communication channel is the entire task surface.
        harden_llm_commands()
        rpc = importlib.import_module("stickerbookrpc")
        request = rpc.current_request("omegallm")
        if not isinstance(request, dict):
            return ""

        safe_input = {
            "text": request.get("text"),
            "principal": request.get("principal"),
            "scene": request.get("scene"),
            "reference": request.get("reference"),
        }
        try:
            provider_id, model, preset = clean_inference(
                request.get("inference"))
            raw = self._transport(preset).complete(
                model, safe_input, min(int(max_tokens), 1200))
            decoded = _parse_json_object(raw)
            if set(decoded) - {"reply", "goal"}:
                raise ValueError("unknown response field")
            reply = decoded.get("reply")
            if not isinstance(reply, str) or not reply.strip():
                raise ValueError("missing reply")
            reply = reply.strip()
            if len(reply) > MAX_REPLY_CHARS:
                raise ValueError("reply too long")
            result = {
                "ok": True,
                "reply": reply,
                "inference": {"provider": provider_id, "model": model},
            }
            goal = clean_goal(decoded.get("goal"))
            validate_demonstration_goal(goal, safe_input["scene"])
            if goal is not None:
                result["goal"] = goal
        except Exception as exc:  # every model/provider/schema failure is bounded
            logger.warning(
                "[stickerbook-llm] failed closed: %s: %s",
                type(exc).__name__, str(exc)[:300])
            result = {"ok": False, "error": "omegallm-failed-closed"}

        if not rpc.stage_result(result):
            logger.warning("[stickerbook-llm] failed to stage bounded response")
            return ""
        return "sb-return"


def loadOmegaPlugin():
    # Early hardening, repeated at start/chat after all plugins have loaded.
    harden_llm_commands()
    providers.registerLLMProvider("StickerBookLLM", StickerBookLLMProvider())
